# Generated by Django 3.2.5 on 2021-07-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_onyx', models.CharField(max_length=5)),
                ('contact', models.CharField(max_length=255)),
                ('qr', models.CharField(max_length=255)),
            ],
        ),
    ]
