# Generated by Django 3.2.5 on 2021-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210731_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка на скачивание контакта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_onyx',
            field=models.CharField(default=1, max_length=3, verbose_name='ID на Onyx-realty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default=1, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lc_onyx',
            field=models.CharField(default=1, max_length=255, verbose_name='Страничка на сайте Onyx с объектами'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото сотрудника'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qr',
            field=models.CharField(default=1, max_length=25, verbose_name='QR code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='share',
            field=models.CharField(default=1, max_length=255, verbose_name='Ссылка для Поделиться'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='area_1_0',
            field=models.CharField(default='rgba(0, 67, 78, 1)', max_length=255, verbose_name='Цвет кнопки 1'),
        ),
    ]
