# Generated by Django 3.2.5 on 2021-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210731_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area_1_1',
            field=models.CharField(default='display: none;', max_length=255, verbose_name='Поле видимости кнопки 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='area_1_2',
            field=models.CharField(default='rgba(0, 67, 78, 1)', max_length=255, verbose_name='Цвет кнопки 1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_1_0',
            field=models.CharField(default='Кнопка 1', max_length=255, verbose_name='Кнопка 1'),
        ),
    ]
