# Generated by Django 3.2.5 on 2021-08-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210803_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lc_onyx',
        ),
    ]
