# Generated by Django 3.2.5 on 2021-08-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_lc_onyx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_1_0',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share',
        ),
        migrations.AddField(
            model_name='user',
            name='power',
            field=models.CharField(choices=[('display: flex;', 'Включить'), ('display: none;', 'Включить')], default=1, max_length=255, verbose_name='power'),
            preserve_default=False,
        ),
    ]
