# Generated by Django 3.2.5 on 2021-08-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_user_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area_1_1',
        ),
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки'),
        ),
    ]
