# Generated by Django 3.2.5 on 2021-08-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210805_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icons',
            field=models.CharField(choices=[('tel', 'Телефон'), ('viber', 'Viber'), ('email', 'Email')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
