# Generated by Django 3.2.5 on 2021-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210805_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('mailto:', 'Email')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
    ]
