# Generated by Django 3.2.5 on 2021-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_user_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
    ]
