# Generated by Django 3.2.5 on 2021-08-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_user_api_cho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='api_cho',
            new_name='b10_api_cho',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='api_inp',
            new_name='b10_api_inp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='b_text',
            new_name='b10_b_text',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='color',
            new_name='b10_color',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='icons',
            new_name='b10_icons',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='title',
            new_name='b10_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='power',
        ),
        migrations.AddField(
            model_name='user',
            name='b10_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 10'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b11_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 11'),
        ),
        migrations.AddField(
            model_name='user',
            name='b11_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b12_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b12_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b12_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b12_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b12_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b12_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 12'),
        ),
        migrations.AddField(
            model_name='user',
            name='b12_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b13_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b13_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b13_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b13_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b13_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b13_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 13'),
        ),
        migrations.AddField(
            model_name='user',
            name='b13_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b14_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b14_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b14_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b14_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b14_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b14_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 14'),
        ),
        migrations.AddField(
            model_name='user',
            name='b14_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b15_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b15_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b15_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b15_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b15_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b15_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 15'),
        ),
        migrations.AddField(
            model_name='user',
            name='b15_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b1_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b1_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b1_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b1_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b1_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b1_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='b1_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b2_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b2_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b2_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b2_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b2_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b2_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='b2_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b3_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b3_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b3_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b3_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b3_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b3_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 3'),
        ),
        migrations.AddField(
            model_name='user',
            name='b3_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b4_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b4_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b4_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b4_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b4_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b4_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 4'),
        ),
        migrations.AddField(
            model_name='user',
            name='b4_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b5_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b5_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b5_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b5_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b5_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b5_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 5'),
        ),
        migrations.AddField(
            model_name='user',
            name='b5_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b6_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b6_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b6_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b6_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b6_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b6_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 6'),
        ),
        migrations.AddField(
            model_name='user',
            name='b6_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b7_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b7_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b7_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b7_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b7_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b7_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 7'),
        ),
        migrations.AddField(
            model_name='user',
            name='b7_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b8_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b8_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b8_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b8_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b8_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b8_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 8'),
        ),
        migrations.AddField(
            model_name='user',
            name='b8_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b9_api_cho',
            field=models.CharField(choices=[('tel:+7', 'Телефон'), ('https://api.whatsapp.com/send?phone=7', 'Whatsapp'), ('https://t.me/', 'Telegram'), ('viber://mobile?number=+7', 'Viber'), ('mailto:', 'Email'), ('https://www.instagram.com/', 'Instagram'), ('https://www.facebook.com/', 'Facebook'), ('https://vk.com/', 'Vk'), ('https://ok.ru/', 'Однокласники'), ('https://www.tiktok.com/', 'Tiktok'), ('https://twitter.com/', 'Twitter'), ('https://www.youtube.com/channel/', 'Youtube'), ('https://ru.linkedin.com', 'Linkedin'), ('https://', 'Ссылка')], default='tel:+7', max_length=355, verbose_name='Функционал кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b9_api_inp',
            field=models.CharField(default='8 800 200 06 07', max_length=255, verbose_name='Ваши данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='b9_b_text',
            field=models.CharField(default=1, max_length=255, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='b9_color',
            field=models.CharField(choices=[('background-color: rgba(0, 67, 78, 1);', 'Темно-Зеленый'), ('background-color: rgba(18, 180, 30, 1);', 'Светло-Зеленый'), ('background-color: rgba(0, 136, 204, 1);', 'Голубой'), ('background-color: rgba(121, 59, 170, 1);', 'Фиолетовый'), ('background-color: rgba(255, 0, 0, 1);', 'Красный'), ('background-color: rgba(35, 31, 32, 1);', 'Черный')], default='background-color: rgba(0, 67, 78, 1);', max_length=255, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='user',
            name='b9_icons',
            field=models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('email', 'Email'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'Vk'), ('ok', 'Однокласники'), ('tiktok', 'Tiktok'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('link', 'Ссылка')], default='tel', max_length=255, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='user',
            name='b9_power',
            field=models.CharField(choices=[('display: none;', 'Выключить'), ('display: flex;', 'Включить')], default='display: none;', max_length=255, verbose_name='Включение кнопки 9'),
        ),
        migrations.AddField(
            model_name='user',
            name='b9_title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
